## Default values for minemeld.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: paloaltonetworks/minemeld
  pullPolicy: IfNotPresent
  # defaults to appVersion
  tag: ""
imagePullSecrets: []

## upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate
replicaCount: 1

service:
  type: ClusterIP
  port: 443
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

# Enable persistence using Persistent Volume Claims
# ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  enabled: false
  local:
    accessMode: ReadWriteOnce
    size: 10Gi
    ## If undefined (by default) the default provisioner will be used
    storageClass:
    annotations: {}
    ## Specify the name of an existing PVC if you want to reuse it
    # existingClaim:
  log:
    accessMode: ReadWriteOnce
    size: 10Gi
    ## If undefined (by default) the default provisioner will be used
    storageClass:
    annotations: {}
    ## Specify the name of an existing PVC if you want to reuse it
    # existingClaim:

customTLS:
  enabled: false
  secret:

securityContext:
  privileged: true

nameOverride: ""
fullnameOverride: ""
deploymentAnnotations: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}